# Retrieve some pieces of information through a dialogue with the user.

std_skills/Meta meta

# The ID of the person to interact with.
# If empty, any user can be interacted with.
string person_id

# The ID of the group of persons to interact with.
# If empty, any group of persons can be interacted with.
# If not empty, the 'person_id' field should be ignored.
string group_id

# The JSON dictionary of pieces of information to be retrieved through the dialogue.
# The keys correspond to the info required, while the values to the data type of the info.
string queries

---
std_skills/Result result

# The JSON dictionary of values obtained from the dialogue,
# where the keys correspond to the 'queries' fields.
# If the piece of information relative to a key could not be retrieved,
# its associated value is null.
string answers

---
std_skills/Feedback feedback
